name: CI

on:
  pull_request:
  push:
    branches: [develop, main]

jobs:
  ci:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read

    container:
      image: ghcr.io/getsyntegrity/syntegrity-ci:0.0.3
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run CI
        run: syntegrity-ci run --profile go-library